version: "3.9"

services:
  hub:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${UDP_PORTS}
      - ${TCP_PORTS}
    volumes:
      - $PWD/data:/data
      - $PWD/plugins:/plugins
    restart: always
    build:
        context: .
        dockerfile: build/Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        cd /pocketmine && \
        php PocketMine-MP.phar --no-wizard --disable-ansi --disable-readline --enable-ansi --enable-readline --data=/data --plugins=/plugins
    networks:
      - servers
networks:
  servers:
