version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  hub:
    image: artent.fun/hub:latest
    container_name: hub
    ports:
      - "19133:19132/udp"
      - "19133:19132/tcp"
    volumes:
      - $PWD/data:/data
      - $PWD/plugins:/plugins
    restart: always
    depends_on:
      - mysql
    build:
        context: .
        dockerfile: build/Dockerfile
    networks:
      - servers
networks:
  servers:
